AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'ec2-snapshot-share

  SAM Template for ec2-snapshot-share

  '
Globals:
  Function:
    Timeout: 30
Resources:
  EC2SnapshotShare:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://your-s3-bucket/0a7f4148f11113c22a426f3222275bb6
      Handler: app.lambda_handler
      Runtime: python2.7
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - ec2:ModifySnapshotAttribute
          Resource: '*'
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - kms:DescribeKey
          - kms:CreateGrant
          - kms:GenerateDataKey
          - kms:ReEncrypt*
          Resource: '*'
      Environment:
        Variables:
          DEST_ACCOUNT: '111111111111'
      Events:
        Event:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
              - aws.ec2
              detail-type:
              - EBS Snapshot Notification
              detail:
                event:
                - createSnapshot
                result:
                - succeeded
Outputs:
  EC2SnapshotShareFunction:
    Description: EC2SnapshotShare Lambda Function ARN
    Value:
      Fn::GetAtt:
      - EC2SnapshotShare
      - Arn
  EC2SnapshotShareIamRole:
    Description: Implicit IAM Role created for EC2SnapshotShareFunction function
    Value:
      Fn::GetAtt:
      - EC2SnapshotShareRole
      - Arn
